### ISSUE TITLE
Consider use of bucklescript fast pipe style

### ISSUE THREAD

**Issue by bordoley** [bordoley/rx-reason#7]
Not sure if it would work for operator chaining but definitely is an option for most apis:

https://bucklescript.github.io/docs/en/fast-pipe.html

**Comment by kennetpostigo** [comment]
Not sure if it compiles to native either

**Comment by bordoley** [comment]
Also it breaks currying and optional parameters (afaict), which some of the apis are designed to support.

**Comment by cem2ran** [comment]
fast pipe works on native (at least when I try with bsb-native). Also I don't think it breaks anything. Correct me if I'm wrong though:
https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBAhgJjEF4IAoB+B7AZpgzuBADADQQAeJAniQF4CUiAfBFruBANRkcQXfUDcAKFCRYMACroATAFZEEOQB8AdNDhoWeMAgCMxCHtpCAUjmXB0Ac2RLVYybKNA

**Comment by bordoley** [comment]
I'm going to close this now that the api is somewhat locked down. Given the use of named parameters and optional parameters throughout the api, I think its better to stick the traditional ocaml argument style.
